# Generated by Django 6.1.1 on 2026-09-25 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('type', models.CharField(choices=[('HOTEL', 'Hôtel'), ('APPARTEMENT', 'Appartement meublé'), ('STUDIO', 'Studio'), ('RESIDENCE', 'Résidence'), ('VILLA', 'Villa'), ('AUBERGE', 'Auberge')], max_length=30)),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, default='', max_length=100)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('nombre_chambres', models.PositiveIntegerField(default=1)),
                ('nombre_lits', models.PositiveIntegerField(default=1)),
                ('nombre_salles_bain', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé'), ('EN_MAINTENANCE', 'En maintenance'), ('MASQUE', 'Masqué')], default='DISPONIBLE', max_length=25)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('politique_annulation', models.TextField(blank=True, default='')),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('regles', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('equipements', models.ManyToManyField(blank=True, related_name='logements', to='logements.equipement')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logements/photos/')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL externe/démo', max_length=500)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('image_principale', models.BooleanField(default=False)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='logements.logement')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
