# Generated by Django 6.1.1 on 2026-09-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logement',
            options={'ordering': ['-date_creation']},
        ),
    ]
